### ISSUE TITLE
Need to handle licensing

### ISSUE THREAD

**Issue by RealGrep** [VsnGamer/ElevatorMod#1]
The mod is listed as All Rights Reserved on CurseForge, and no mod pack permission is explicitly given. I also don't see the license in the source code repository. However, you state that it's a port of OpenBlocks elevators. OpenBlocks is MIT licensed, and so should your mod be, I believe.

Although it's permissive as licenses go, you do still have to include the MIT license text in the software, for example. The text of the license from OpenBlocks: https://minecraft.curseforge.com/projects/openblocks/license . And here's a Wikipedia page on it that might be of use: https://en.wikipedia.org/wiki/MIT_License

I assume you just didn't set the license on CurseForge. Won't take much at all to comply with it. I suggest setting that on CurseForge and including a copy of the license text in your source repo on Github (and no, I am not a lawyer and none of this should be construed as professional legal advice. lol). And people like me ensuring their mod pack follows all the licenses will be grateful. :)

And thanks for porting this. It's really nice to have it, and I appreciate it!

**Comment by VsnGamer** [comment]
Changed to MIT, is it good now ? 
I dont know much about licensing :(

**Comment by RealGrep** [comment]
Good on the Curse side, yeah. You also need to include the MIT license in your source repository, and then you'll be totally compliant. So I'd just toss a file, maybe called something like LICENSE, into the root of your Git repository. Then you're all good!

Thanks for taking care of it! :)

**Comment by VsnGamer** [comment]
Done.
Thanks for the support :)

**Comment by RealGrep** [comment]
No prob! :)
