### ISSUE TITLE
Uncompatible With Latest Forge

### ISSUE THREAD

**Issue by ghost** [VsnGamer/ElevatorMod#10]
[crash-2017-06-24_12.18.36-client.txt](https://github.com/VsnGamer/ElevatorMod/files/1099562/crash-2017-06-24_12.18.36-client.txt)

**Comment by TheXWolf** [comment]
Getting the exact same error, running forge 14.21.0.2362 for 1.12.

**Comment by VsnGamer** [comment]
I am aware, forge is rewriting the registry system.
I think it still works in forge 1.12-14.21.0.2347 and below.
Thanks.

**Comment by MokahTGS** [comment]
Shoot, that's too bad as many of the mods (getting 17 mods with errors) require a higher version of forge than 2347.

**Comment by TheXWolf** [comment]
Ya I was really annoyed when I read the release notes on forge and saw that. Hopefully it's worth the trouble for mod makers. I haven't even started redoing my mod, so much of a chore.

**Comment by VsnGamer** [comment]
This should be fixed in the last build.
Please confirm.
Thanks.
