### ISSUE TITLE
Directional mode Crash

### ISSUE THREAD

**Issue by HarveyTay** [VsnGamer/ElevatorMod#104]
turned directional mode on and my game crashed cant reload into server without crashing
[crash-2022-11-14_15.04.20-client.txt](https://github.com/VsnGamer/ElevatorMod/files/10004226/crash-2022-11-14_15.04.20-client.txt) another 
[crash-2022-11-14_15.01.14-client.txt](https://github.com/VsnGamer/ElevatorMod/files/10004273/crash-2022-11-14_15.01.14-client.txt)

**Comment by VsnGamer** [comment]
Probably OptiFine incompatibility
