### ISSUE TITLE
Camoflage crashes client

### ISSUE THREAD

**Issue by Wraithypooo** [VsnGamer/ElevatorMod#109]
When you camoflage an elevator and tries to break it it crashes the client. And when you remove camoflage it doesn't do it untill you reconnect... 

[crash-2023-02-06_15.44.37-client.txt](https://github.com/VsnGamer/ElevatorMod/files/10664225/crash-2023-02-06_15.44.37-client.txt)

**Comment by VsnGamer** [comment]
It should be fixed in 1.8.11, update the mod and check if it's resolved.
