### ISSUE TITLE
ElevatorMod-1.12-1.3.3.jar crashes

### ISSUE THREAD

**Issue by dragon3025** [VsnGamer/ElevatorMod#11]
Crash log: https://pastebin.com/bZss5rsC

**Comment by VsnGamer** [comment]
Forge [changed](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.0.2379/forge-1.12-14.21.0.2379-changelog.txt) mapping events, should be a quick fix(hopefully).
Btw what forge version are you running ?
Thanks.

**Comment by VsnGamer** [comment]
Try the latest build(1.3.4) please, hope it works !
Thanks.

**Comment by dragon3025** [comment]
I was using forge-1.12-14.21.0.2343-universal. I tried the new version out and it's working. Thanks.
