### ISSUE TITLE
Crasheo al poner ascensor con comandos // Crash when putting elevator with commands

### ISSUE THREAD

**Issue by MonitoEnMotito** [VsnGamer/ElevatorMod#112]
Puse un ascensor con el comando "/setblock" reemplazando un bloque bajo la tierra y luego no pude volver a entrar al mundo, salvo que quite el mod, pero no es la idea.
Intenté quitar el mod, alejarme, poner un bloque de comandos repitiendo "/setblock stone", guardar y salir, y volver a entrar pero con el mod cargando ambas partes pero no funciona.

I put an elevator with the "/setblock" command replacing a block underground and then I couldn't get back into the world. Unless I unmod it, but that's not the idea.
I've tried removing the mod, walking away, putting a command block repeating "/setblock stone", saving and exiting, and back in but with the mod loading both parts but it doesn't work.

[crash-2023-05-11_14.04.52-client.txt](https://github.com/VsnGamer/ElevatorMod/files/11455673/crash-2023-05-11_14.04.52-client.txt)

**Comment by VsnGamer** [comment]
Probably OptiFine incompatibility

**Comment by MonitoEnMotito** [comment]
Thank you very much, I removed it and it worked!
