### ISSUE TITLE
Crash & Render Issues

### ISSUE THREAD

**Issue by tazzy989** [VsnGamer/ElevatorMod#113]
Encountered a strange issue with Elevators. This is in a huge, self-made and self-hosted modpack for a friend and I. The elevators are all appearing black in JEI and have no texture. When placed, it was a void block, then all clients in the vicinity crashed. Clients were able to re-log into the server, but the chunk seems to be unloaded now? I was able to break and destroy the elevator block. 

I included everything I could think of that might be helpful. Latest logs, console logs, and screenshots. 

![image](https://github.com/VsnGamer/ElevatorMod/assets/83916974/44d05893-b64e-4901-a7f6-f298ccbc13d1)
![image](https://github.com/VsnGamer/ElevatorMod/assets/83916974/7b434317-2397-4ff5-8ea7-67e4637bca7a)

Console Logs:
https://paste.atlauncher.com/view/6d19b943-905d-4c01-a096-627bf654b333
[latest.log](https://github.com/VsnGamer/ElevatorMod/files/11876909/latest.log)
[2023-06-26-2.log.gz](https://github.com/VsnGamer/ElevatorMod/files/11876910/2023-06-26-2.log.gz)
[2023-06-26-3.log.gz](https://github.com/VsnGamer/ElevatorMod/files/11876911/2023-06-26-3.log.gz)

**Comment by tazzy989** [comment]
After destroying the block and using F3+A our base seems back to normal.

**Comment by VsnGamer** [comment]
Could not reproduce, the logs don't report anything for the elevator mod. 
However the logs report other errors for example a NPE from sodium when rendering something from frostedglass.
Where the elevators the only things appearing black in JEI?

**Comment by tazzy989** [comment]
Whoops, I figured I'd get an email if I got a reply, guess not. 

I'll see if I can reproduce in a solo world. My logs from that might've been when I reconnected and the chunk was unloaded. It was strange, the server itself didn't crash. 
I'll see if I can grab more useful logs. We had quite a series of render issues in this pack and had to remove Chisel and CTM as well. Not sure what's causing it, I'm not very good at this lol

**Comment by tazzy989** [comment]
I loaded into a single player creative world. All Elevator blocks appear to be black in JEI, as well as Frosted Glass and Frosted Glass Pane, as well as the "Construction Block" from Building Gadgets (but we've used the rest of the building gadgets mod and had no issues). 
I put all 3 of those blocks into my creative inventory, and when I closed the inventory screen, they swapped to their usual colors in my hotbar, rather than being a black/textureless block.
![image](https://github.com/VsnGamer/ElevatorMod/assets/83916974/6e64ffb5-fb83-4ba2-9700-1cdfe5f583a8)

Placing any of the 3 blocks immediately crashes the world.
![image](https://github.com/VsnGamer/ElevatorMod/assets/83916974/03ea46a0-849f-4361-abbb-63c30a74dfc3)

https://paste.atlauncher.com/view/e2ecd93e-95bd-4952-8212-7e54860b50d6

Cleared logs, loaded back in.
![image](https://github.com/VsnGamer/ElevatorMod/assets/83916974/4cb7405c-5eea-473d-a77a-43e0bc287749)

f3+A does not re-render the chunk. 
When breaking the block, the textures are in the classic magenta/black squares. 
After breaking the block, the chunk re-renders with f3+A. 

https://paste.atlauncher.com/view/097e92fa-0b85-4aad-aadf-82484bd51080
Final logs. Please let me know if I can provide any other information or do any other troubleshooting, or if you know what is causing this. I appreciate the help! We miss our elevators xD

Edit: For clarity, elevator blocks result in the exact same crash, I suppose I should've used one of those for the example instead of the construction block.

**Comment by VsnGamer** [comment]
Based on the logs I think it might me a conflict between sodium and frosted glass.
It's weird that elevators result in the same crash, maybe it's because camouflage code tries to render with a layer from frosted glass.
Can you try removing sodium and/or frosted glass and check if it still crashes?
Thanks for your time

**Comment by tazzy989** [comment]
WOOOOO we have elevators again! Thank you so much 😭 I removed frosted glass and both Elevators and the construction block from Building gadgets work again. I'll go drop an issue report in Frosted Glass's curseforge page. Thanks again!
