### ISSUE TITLE
Crash when moving on server

### ISSUE THREAD

**Issue by JoNobre** [VsnGamer/ElevatorMod#115]
when i join the server, it loads, but when i press any key on keyboard it crashes
[crash-2023-07-22_18.09.08-client.txt](https://github.com/VsnGamer/ElevatorMod/files/12137235/crash-2023-07-22_18.09.08-client.txt)

**Comment by VsnGamer** [comment]
Can you try this fix?
[elevatorid-1.19.2-1.8.10.zip](https://github.com/VsnGamer/ElevatorMod/files/12146393/elevatorid-1.19.2-1.8.10.zip)

**Comment by JoNobre** [comment]
it fixed the crashing on input problem, but now it's weird, the player doesn't move a inch when i press wasd, my hand for some reason is lower than it should be and the only the lower layer of my skins shows, i'm still gonna see with the server owner if it is a bug with the server.
Also, i don't know if i used it right, i'm supposed to switch the extention to .jar or just place the .zip on the mod folder, i did the .jar worked but still.
In single player is fine tho

**Comment by JoNobre** [comment]
yeah it's a glitch where i can't move at all, and a lot of things are wrong as well, when i pick up an item the sprite is weird on the hotbar, dying or changing gamemode doesn't help, tried to clear my .minecraft and all but still the same thing
i don't know if this glitch now has to do with your mod, it may be, it may not, at least the file you sent me stopped the game of crashing so thanks, now i'm gonna try to solve the other problem

**Comment by FoxMcloud5655** [comment]
This same issue is happening on 1.20.1, just differently.  The client sometimes will randomly crash when traveling DIMs, particularly from the Overworld to the Nether.  Relevant part of the crash report below:
```
java.lang.NullPointerException: Cannot read field "f108573" because "player.f108618" is null
    at xyz.vsngamer.elevatorid.ElevatorHandler.onInput(ElevatorHandler.java:31) ~[elevatorid-1.20.1-1.8.14.jar%23467!/:1.20.1-1.8.14] {re:classloading}
    at xyz.vsngamer.elevatorid.__ElevatorHandler_onInput_InputEvent.invoke(.dynamic) ~[elevatorid-1.20.1-1.8.14.jar%23467!/:1.20.1-1.8.14] {re:classloading,pl:eventbus:B}
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
```
It might be due to a mod conflict or a new function added, if I had to hazard a guess.  I can ask the player to send the entire crash report if needed.

**Comment by FoxMcloud5655** [comment]
The developer of Enchant With Mobs pushed an update that fixes this exact issue.  I'm pretty sure it was a mod conflict issue and this issue can safely be closed.

**Comment by JoNobre** [comment]
reopening just to say that i don't have the crashing problem anymore, but i have another problem and i'll just place the reddit i made trying to get help and let this open for a bit to see if anyone know a way to help, sorry if this is incovenient

https://www.reddit.com/r/Minecraft/comments/159drwd/cant_move_in_my_friends_modded_server/
