### ISSUE TITLE
[1.20.1] Rain goes through the elevators

### ISSUE THREAD

**Issue by TiphaineLAURENT** [VsnGamer/ElevatorMod#116]
As you can see in the image, rain goes through the elevators. I tested with and without camouflage and the issue is the same.
![image](https://github.com/VsnGamer/ElevatorMod/assets/25824254/6b8ed7ed-ac8c-4ca9-a6e3-952eaec25807)

Minecraft: 1.20.1
OpenBlocks Elevator: 1.20.1-1.8.14
Forge: 47.1.3

**Comment by VsnGamer** [comment]
Please try version 1.20.1-1.8.15
