### ISSUE TITLE
[1.20.1] Game crashes when I enter the server (Elevator + Edivadlib)

### ISSUE THREAD

**Issue by lays24mc** [VsnGamer/ElevatorMod#117]
Hi,

As soon as I use the latest version of EdivadLib 2.0.1 and OpenElevator is installed with it, I can't join my server anymore. I come to the world and the client crashes. Downgrade I EdivasLib again to 2.0.0  it works.

Mods:
EdivadLib 2.0.1
OpenBlocks Elevator 1.8.15
Forge 47.1.3
Crashlog: https://pastebin.com/98v0J0tS

**Comment by VsnGamer** [comment]
Please try version 1.20.1-1.9

**Comment by lays24mc** [comment]
Sorry for the late reply. Works fine with this version :)
