### ISSUE TITLE
Elevator Mod requires javafml:47

### ISSUE THREAD

**Issue by Neon4UltraPlays** [VsnGamer/ElevatorMod#118]
![image](https://github.com/VsnGamer/ElevatorMod/assets/90380800/7e619630-cfa7-4b3a-adfb-061ad0d6b4fa)
Hello OBE mod,

I encountered an error while opening MInecraft. It says I need "javafml:47". Can you help fix this bug? Otherwise I can't play Minecraft!

Thank you!
[crash-2023-09-07_07.40.53-fml.txt](https://github.com/VsnGamer/ElevatorMod/files/12543457/crash-2023-09-07_07.40.53-fml.txt)

Version: ForgeOptifine 1.18.2

**Comment by VsnGamer** [comment]
Download a mod version for Minecraft 1.18.2
