### ISSUE TITLE
Crash in modpack

### ISSUE THREAD

**Issue by MostlyPride** [VsnGamer/ElevatorMod#119]
Now while I know this isn't a direct issue with the ElevatorMod itself. I was hoping we could figure out what is triggering it and fix it!

**Describe the Bug**
I had some friends place elevator blocks in their base and use them just fine for a while.

Once midnight hit, the server stopped. Backed up. Then did a reboot. Upon them attempting to reconnect the server would crash.

To fix this issue I disabled the mod "elevatorid-1.20.1-1.8.15.jar". Located the areas that the elevator blocks were placed and replaced the blocks there with another.

After re-adding the same version of the mod, the server booted up normally and everyone could connect.
 
 **Reproduction Steps**
1.Place elevator blocks.
2.Have the server shut down and then start up
3.Have players attempt to reload the chunk/area of the placed elevator blocks.
...Crash
 
 
 **Screenshots and Videos**
![image](https://github.com/VsnGamer/ElevatorMod/assets/10325931/17722404-005c-47aa-a0d4-fc41f827fa21)
![image](https://github.com/VsnGamer/ElevatorMod/assets/10325931/60e253de-66a4-45c0-b5aa-af2c1c8e8a2e)
![image](https://github.com/VsnGamer/ElevatorMod/assets/10325931/a88a7cde-e13f-4da0-96cf-e6fe1cd2d32c)

These where the oak wood logs are is where the elevator blocks were placed. Just providing the best info I can in hopes that the bug can be fixed or patched.

**Crash Report or Log**
https://gist.github.com/MostlyPride/0db7bc34bc0f024aae794d97f0991f0d

**Operating System**
Windows 10

**Minecraft Version**
1.20

**Modloader**
Forge

**Modpack Version**
Better MC [Forge] 1.20.1 v12 HF - (Beta) - (Current)

**Comment by VsnGamer** [comment]
I know it's not a fix but can you try removing starlight and check if it still happens?
_In 1.20 Mojang closed the performance gap between vanilla and starlight so you should still have good performance_

**Comment by MostlyPride** [comment]
I can definitely give that a shot. Will update you once I've done it.

**Comment by TigerWalts** [comment]
Running into this on the Better Minecraft Forge 1.20 (BMC4) modpack.

Disabling Starlight doesn't solve the problem. The elevator code that hangs is still being triggered by the vanilla lighting code.

I suspect that the block data has a lock on it at the time the elevator code is being called. Crash report (with Starlight, without it just hangs):

Main Thread:

https://gist.github.com/TigerWalts/485070c85c155e05557b06af8d6acc1c#file-crash-2023-09-23_22-52-39-server-txt-L15-L37

Worker Thread:

https://gist.github.com/TigerWalts/485070c85c155e05557b06af8d6acc1c#file-crash-2023-09-23_22-52-39-server-txt-L402-L442

**Comment by KernfusionGit** [comment]
I don't know why, but claiming the chunk containing the elevatorblocks and setting it to forceloadable using open-parties-and-claims stops the server from crashing.

Working on:
open-parties-and-claims-forge-1.20.1-0.20.1
elevatorid-1.20.1-1.8.15
forge-47.2.0

**Comment by KernfusionGit** [comment]
Okay forget my previous comment, its the camouflage. As long as the elevatorblocks are not camouflaged it works fine.

Would it be possible to disable the camo feature in the config file, as a hotfix?

**Comment by VsnGamer** [comment]
I still haven't been able to reproduce this, I'm running NeoForge so it could be a incompatibility with LexForge.
I'll try to compile a 1.20.1 version with LexForge and post it here.

@KernfusionGit unfortunately there is currently no config option for that :(

**Comment by VsnGamer** [comment]
Please try version 1.20.1-lex-1.9

**Comment by KernfusionGit** [comment]
where can i find that version of the mod?

**Comment by VsnGamer** [comment]
Curseforge is taking a while to review it...

You can find a copy in my last comment in #121 if you don't want to wait.

**Comment by KernfusionGit** [comment]
Seems to be working!
