### ISSUE TITLE
Elevator Mod freezes chunks when players log out while standing on elevator block 

### ISSUE THREAD

**Issue by luis-vico** [VsnGamer/ElevatorMod#121]
The mod ran fine until one of the players on my server apparently logged out while standing on an elevator block in his base. The next time a player tried to load the chunks or the player tried to log back in the server would respond with something along the lines of "susspicious async chunk load" and then time out. The server then looped with this error message: 
_[spark-asyncsampler-worker-thread/WARN] [spark/]: Timed out waiting for world statistics_

After restarting the server everything was fine until someone tried to load the same chunks and it would repeat. After removing the mod the issue was fixed. 

*Im not completely sure if it was the logging out while standing on the block or some server related issue with backing up the world but the mod was definitly the root cause.

**Comment by luis-vico** [comment]
I also downloaded the wold and tried loading the same map in single player but as soon as I load the chunk my single player world freezes and I cant interact with anything. 
When trying to close the game it crashes.

**Comment by VsnGamer** [comment]
Hi, what mod version are you running? NeoForge or LexForge? Got any logs?

**Comment by luis-vico** [comment]
> Hi, what mod version are you running? NeoForge or LexForge? Got any logs?
The severs was running the Better MC v16 Modpack. I updated the elevator Mod to the latest Version and it was still present. 

I can follow up with the severs logs later today. 

Im also not sure if the bug is limited to players logging out on the block or not. Yesterday the issue appeared after one of the players switched dimensions and after returning to his base the server timed out responding with the same message.

**Comment by luis-vico** [comment]
> Hi, what mod version are you running? NeoForge or LexForge? Got any logs?

The server was running the Better MC v16 Modpack (Forge). I also updated the Mod to the latest Version and the issue presisted

**Comment by luis-vico** [comment]
[crash-2023-10-28_14.05.04-server.txt](https://github.com/VsnGamer/ElevatorMod/files/13231853/crash-2023-10-28_14.05.04-server.txt)
[crash-2023-10-28_14.12.12-server.txt](https://github.com/VsnGamer/ElevatorMod/files/13231854/crash-2023-10-28_14.12.12-server.txt)
[crash-2023-10-28_17.52.01-server.txt](https://github.com/VsnGamer/ElevatorMod/files/13231855/crash-2023-10-28_17.52.01-server.txt)
Here are some of the crash reports. The Server is running on 1.20.1

**Comment by VsnGamer** [comment]
I've just uploaded a new version (1.20.1-lex-1.9), can you try it?

**Comment by luis-vico** [comment]
> I've just uploaded a new version (1.20.1-lex-1.9), can you try it?

I'll put it back on the server immediately.

**Comment by luis-vico** [comment]
> I've just uploaded a new version (1.20.1-lex-1.9), can you try it?

I can't seem to find it. Can you give me the link? The most recent upload I see is version 1.20.2-1.9.2 from 2 days ago.

**Comment by VsnGamer** [comment]
It's still under review, they are taking a while with this one...

Here's a copy: 
[elevatorid-1.20.1-lex-1.9.jar-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/13251855/elevatorid-1.20.1-lex-1.9.jar-unzip-me.zip)

**Comment by luis-vico** [comment]
> It's still under review, they are taking a while with this one...
> 
> Here's a copy: [elevatorid-1.20.1-lex-1.9.jar-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/13251855/elevatorid-1.20.1-lex-1.9.jar-unzip-me.zip)

Thank you. Mod is running on the server. I'll report back if any other issues come up.

**Comment by luis-vico** [comment]
> > It's still under review, they are taking a while with this one...
> > Here's a copy: [elevatorid-1.20.1-lex-1.9.jar-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/13251855/elevatorid-1.20.1-lex-1.9.jar-unzip-me.zip)
> 
> Thank you. Mod is running on the server. First thing: It seems the mod reset my xp level on the server? In single player it did not. I'll report back if any other issues come up.

My XP on the server keeps reseting for some reason. I have not figuered out what causes it.

**Comment by VsnGamer** [comment]
If it goes back to normal when you pick up XP, it's just a client bug:
https://bugs.mojang.com/browse/MC-124177

**Comment by luis-vico** [comment]
> If it goes back to normal when you pick up XP, it's just a client bug: https://bugs.mojang.com/browse/MC-124177

No, the xp bar does not reset but the full levels do. If I pick up xp after it resets I start at 1.
