### ISSUE TITLE
Game crashes upon start (NeoForge 1.20.4)

### ISSUE THREAD

**Issue by Mrbysco** [VsnGamer/ElevatorMod#125]
### What happened?
When I tried to boot up the mod (Version **1.20.4-1.9.6**) in NeoForge **20.4.152-beta** it crashed with a NullPointerException.

### Steps to reproduce
1. Install NeoForge 20.4.152-beta
2. Install Elevator Mod version 1.20.4-1.9.6
3. Start the game
4. Crash

### Crash report
https://pastebin.com/Jw5hiDeT

**Comment by Mrbysco** [comment]
As a dev myself I cloned the repo to see if I could PR a fix but somehow the issue doesn't happen in the dev client

**Comment by VsnGamer** [comment]
Can you try again with the latest commit?

**Comment by Mrbysco** [comment]
Yup with the latest commit a build will work outside of dev
