### ISSUE TITLE
spamming elevator lags server

### ISSUE THREAD

**Issue by creaper3** [VsnGamer/ElevatorMod#127]
If you spam up and down (space and shift) really fast, the tps will drop. It could be used on servers to bring them down.

EDIT: This works for me with the Entangled Mod when hiding the elevator.

**Comment by VsnGamer** [comment]
Hello, is this a public server? Are autoclick tools involved?
For public servers, limiting the packet rate can help with issues like this.
Generally a single player spamming shouldn't be much of a problem, unless the server hardware is really low-end.
