### ISSUE TITLE
Elevator Block Camouflage works with glow stone but only stay lit until you teleport away, even when chunkloaded 

### ISSUE THREAD

**Issue by Arcitect-X** [VsnGamer/ElevatorMod#131]
Hi, discovered a possible issue when using camo on elevator blocks.  Playing TNP 7 (ver 1.14) on forge which is 1.20.1 mc ver)   If you take a glow stone and put it as camouflage on the elevator, the elevator now glows, however traveling away from the elevator and coming back it now does not glow.  also happens on chiseled glow stone or the verdant froglight.  The elevator is in a chunkloaded chunk.

**Comment by VsnGamer** [comment]
Hello, I believe this is fixed in d3ac259150dc3a8b6107ef6fffad58f3ab055eb1 by using https://github.com/neoforged/NeoForge/pull/464

However, I don't think this was backported to 1.20.1 so I don't think it can be fixed without adding some blockstate property

**Comment by Arcitect-X** [comment]
Ok great thanks
