### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fireworkstars46** [VsnGamer/ElevatorMod#136]
Do you have discord?

**Comment by VsnGamer** [comment]
If you have any question you can ask it here.

**Comment by Fireworkstars46** [comment]
My question is, is it possible for the elevator to be moving instead of teleport?

**Comment by VsnGamer** [comment]
I believe there are a few mods that do what you want.
I don't remember exact names but you should be able to find them easily.

**Comment by Fireworkstars46** [comment]
I mean the mod from you (open blocks)
