### ISSUE TITLE
Use BlockStates instead of many different blocks

### ISSUE THREAD

**Issue by magneticflux-** [VsnGamer/ElevatorMod#14]
Using unique blocks for each color of teleporter is redundant, since color functionality is available through properties. Wool uses the color property, and you can learn more about them [here](https://mcforge.readthedocs.io/en/latest/blockstates/states/).

I'm new to Minecraft modding, so I'm not entirely confident yet, but I could try my hand at fixing it and allow worlds to be migrated using the MissingMappings event. If you want, I'll make a pull request with my attempts so you can look over it.

EDIT: I'm also using the Minecraft Modding plugin for Intellij IDEA, which highlights a bunch of common errors and speeds up modding a lot, so if you use Intellij you should definitely check that out.

**Comment by magneticflux-** [comment]
Nevermind; after a few hours of trawling through Google and various forums, I have come to the conclusion that registering items for blocks that have variants is really difficult when it probably shouldn't be.

**Comment by VsnGamer** [comment]
No idea how to do that xD
But Ill read what you have sent
Thanks !

**Comment by magneticflux-** [comment]
@VsnGamer I might keep experimenting with it, but I'm pretty new to modding and there isn't a whole lot of documentation at all unfortunately. I'm going to base my attempts off of how Rockwool is made in Thermal Foundation, located [here](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/block/BlockRockwool.java).

Looking at all of the CoFH Core stuff, it looks really useful. [This class](https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/block/BlockCoreTile.java) in particular stands out. What do you think about adding a dependency on [CoFH Core](https://github.com/CoFH/CoFHCore)? It's already used by tons of other mods, so users will probably already have it installed.

**Comment by magneticflux-** [comment]
@VsnGamer I've got it working locally! I'll push my changes to a branch tonight if all goes well. I pretty much based everything off of Thermal Foundation, and I used CoFHCore to reduce redundant stuff for registering things.

**Comment by VsnGamer** [comment]
Nice, I think I can make the mod independent after that, (also giving the proper credits)

**Comment by VsnGamer** [comment]
The flattening happened.
