### ISSUE TITLE
Ability to redye elevator blocks

### ISSUE THREAD

**Issue by MurphysChaos** [VsnGamer/ElevatorMod#18]
It would be nice to be able to repurpose an elevator with a new dye. The following code works in 1.11.2 but doesn't work in 1.12 due to the new .json format recipes. The code must be inserted into ModCrafting.java inside the existing for loop.

```
for (EnumDyeColor elevatorColor : EnumDyeColor.values()) {
	GameRegistry.addShapelessRecipe(new ItemStack(ModItems.elevators.get(color)),
			new ItemStack(ModItems.elevators.get(elevatorColor)),
			// Wool, glass, and clay use the damage color
			new ItemStack(Items.DYE, 1, color.getDyeDamage())
	);
}
```

**Comment by ghost** [comment]
I agree. That would be great!

**Comment by VsnGamer** [comment]
Please test in version 1.12.2-1.3.10
Thanks

**Comment by VsnGamer** [comment]
I'm assuming this is working as of v1.12.2-1.3.10, closing.
