### ISSUE TITLE
Elevators only work if they’re the same colour

### ISSUE THREAD

**Issue by ghost** [VsnGamer/ElevatorMod#20]
Is this intended? I like matching the elevator with the floor, so I like having different coloured elevators, but that doesn’t work.

It’d be fantastic if you could use different coloured elevator blocks!

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**OpenBlocks Elevator version**: 1.3.5

**Comment by VsnGamer** [comment]
It is intended, but I will try adding a config for that.
