### ISSUE TITLE
Elevators work for spectators

### ISSUE THREAD

**Issue by dougwebb** [VsnGamer/ElevatorMod#21]
Not sure if this is intended, unintended, or a bug, but if you go into spectator mode and fly up or down through an elevator block, the block will be activated. I don't know if non-spectator players on a server would hear the whoosh sound.

Discovered in ElevatorMod-1.12.2-1.3.5.jar, in Direwolf20 1.12 Pack v1.3.0

**Comment by VsnGamer** [comment]
Should be fixed next update
