### ISSUE TITLE
Player disconnected from the server if walking over a white elevator block. NPE

### ISSUE THREAD

**Issue by ProsperCraft** [VsnGamer/ElevatorMod#23]
https://gist.github.com/ProsperCraft/32e7d0924583d2cda8601a08fc65f9bb

Tested and reproduced.

https://gist.github.com/ProsperCraft/f9cc05ec36e464fa31609d4e77968432

and again...

https://gist.github.com/ProsperCraft/99dd394154c916c1df759212613d5710

It only seems to be white, when it has a block camouflage it doesn't disconnect the player.

**Comment by litjohn50** [comment]
From me investigating it was just right clicking the elevator, while a player was near it (do not have to be standing ontop at the time).

**Comment by rodrigoaddor** [comment]
I've been able to reproduce it easily. In a server, when I change the camouflage with another player nearby, he gets disconnected

**Comment by VsnGamer** [comment]
Can you test version 1.12.2-1.4.2 ?
Remember it no longer requires Bookshelf as a dependency.
Also old version camo may or may not break.
Thanks.
