### ISSUE TITLE
Glass Elevators and Private ?

### ISSUE THREAD

**Issue by ghost** [VsnGamer/ElevatorMod#25]
Could you please make glass variants of the Elevators - I have a glass floor in my base

Also maybe a way to make them private/public or (if FTB installed) Team only ?

Love the mod, thank you.

**Comment by VsnGamer** [comment]
You can try the **experimental** 1.4.1 version and camouflage the elevator with any glass.
Just right click with the glass on the elevator.

**Comment by VsnGamer** [comment]
@MeinKraft does version 1.12.2-1.4.1 work for your needs (camouflage wise) ?

**Comment by ghost** [comment]
sorry for the late reply. I dont even remembering asking for this lol.  It works fantastic. Love the glass.  Could you add an Information tab into JEI so the user knows they can right click glass to it.  Otherwise theres no way of knowing

thanks

**Comment by VsnGamer** [comment]
Something like this?
![Screenshot_2019-05-05_20-04-29](https://user-images.githubusercontent.com/18006201/57320805-accf2380-70f7-11e9-88ce-cfa56aa424bb.png)

**Comment by ghost** [comment]
Looking good, sir !

**Comment by VsnGamer** [comment]
Try version 1.4.2 please,
Thanks.

**Comment by VsnGamer** [comment]
JEI information seems to work fine, closing.
