### ISSUE TITLE
Elevator skips floors

### ISSUE THREAD

**Issue by Brycey92** [VsnGamer/ElevatorMod#27]
If you have 3 elevator blocks vertically, and the top pair have 2 air blocks between them, pressing shift on the top one will send you down 2 floors.

**Comment by VsnGamer** [comment]
Should be fixed next release

**Comment by VsnGamer** [comment]
@Brycey92  Please confirm fix on version 1.3.7
Edit: version 1.3.8

**Comment by Brycey92** [comment]
Thanks for the fix! I'll test the update when I have enough time.

**Comment by VsnGamer** [comment]
Im assuming this is fixed, closing.
