### ISSUE TITLE
Elevators treat vanilla barrier blocks as non-solid blocks.

### ISSUE THREAD

**Issue by monodemono** [VsnGamer/ElevatorMod#31]
The ability to elevator up into non-solid blocks is cool in some circumstances, because it lets you decorate and hide elevators, but barrier blocks are intended to block player movement for a reason, and this can cause issues.

One example of this in Sky Factory 4's compact machines world type, the Twilight Forest is a compact machine cube at the world height limit, and the top of it is a layer of barrier blocks. However, if a player places an elevator as high as they can, and then rides the elevator up, they're able to do so successfully, clipping into the barrier block. Then all they have to do is jump once to be on top of it, and run around freely.

The main fix that needs to be done here is to block elevators from letting people warp into barrier blocks.

To build on this, a blacklist in the config would be nice incase something similar comes up in the future, it would allow for modpack developers to block warping into specific types of blocks that might be used in specific ways.

**Comment by VsnGamer** [comment]
Thanks for the report,
What version does this occur ?

**Comment by monodemono** [comment]
1.12.2-1.3.8

**Comment by VsnGamer** [comment]
Please confirm fix on version 1.3.9

**Comment by monodemono** [comment]
Just tested it, and it's working perfect now, thank you very much :)
