### ISSUE TITLE
Suggestion: Config option to limit the elevators max Distance

### ISSUE THREAD

**Issue by SirAron111** [VsnGamer/ElevatorMod#34]
I like the mod but I am missing one feature I really liked from the open blocks version. And that is the feature to limit the Distance of the Elevator Blocks until a new one is needed. Would it be possible to add this feature in?

**Comment by VsnGamer** [comment]
Should be doable, what minecraft version are you in ?

**Comment by SirAron111** [comment]
1.12.2

**Comment by VsnGamer** [comment]
Please test version 1.12.2-1.3.11

**Comment by SirAron111** [comment]
I did and it works great just missing tests on server side. Will add once i finished these.
EDIT: Love it works great even on servers.

**Comment by VsnGamer** [comment]
Great !
