### ISSUE TITLE
 ClassInheritanceMultiMap asynchronously.

### ISSUE THREAD

**Issue by kristi71111** [VsnGamer/ElevatorMod#35]
Not really sure if I should report this here or not however. I get this spammed on console from time to time. And it references this mod.

[java.lang.Thread:dumpStack:1336]: at xyz.vsngamer.elevator.network.TeleportHandler.onMessage(TeleportHandler.java:35)
[java.lang.Thread:dumpStack:1336]: at xyz.vsngamer.elevator.network.TeleportHandler.onMessage(TeleportHandler.java:17)

Just tested again the spam does indeed come from the elevator mod being used.
Using spongeforge version 1.12.2-2838-7.1.7-RC3866

Glist: [Full output](https://gist.github.com/kristi71111/737e2b66df375eae3e2b4c4b6f589312)

**Comment by VsnGamer** [comment]
I have a guess to what it may be, will look into it later.
Does it happen with normal forge ?

**Comment by kristi71111** [comment]
> I have a guess to what it may be, will look into it later.
> Does it happen with normal forge ?

Does not happen in a pure forge enviroment.

**Comment by VsnGamer** [comment]
Can you test this ? (extract and install normally)

[ElevatorMod-1.12.2-1.3.12.zip](https://github.com/VsnGamer/ElevatorMod/files/3471728/ElevatorMod-1.12.2-1.3.12.zip)

**Comment by kristi71111** [comment]
> Can you test this ? (extract and install normally)
> 
> [ElevatorMod-1.12.2-1.3.12.zip](https://github.com/VsnGamer/ElevatorMod/files/3471728/ElevatorMod-1.12.2-1.3.12.zip)

With this I can't replicate the error

**Comment by kristi71111** [comment]
However it does seem like it just skips the blocks in between elevators and goes to the highthest or lowest elevator point.
