### ISSUE TITLE
Elevator blocks not showing up in creative, or tabs

### ISSUE THREAD

**Issue by bloodconfetti** [VsnGamer/ElevatorMod#36]
![elevator problem](https://user-images.githubusercontent.com/53692357/62754382-d23c3800-ba2c-11e9-917c-e4f959bb612b.png)

No idea what's happened here, but I downloaded the mod, put it in my mods folder, logged in (Forge: 28.0.45, Minecraft: 1.14.4, mod version: ElevatorMod-1.14.4-1.3.11) and I opened the inventory, scrolled to the blank tab and... yeah. Sorry. Not sure what other information you need.

I currently have the following mods:
![mods so far](https://user-images.githubusercontent.com/53692357/62754480-39f28300-ba2d-11e9-9f35-a7f4e5134062.png)

eta: I don't think this is an issue with your mod, but Forge or myself, because now the same thing has happened to two other mods...
forbidden_arcanus-1.14.4-1.0-Beta-2
https://github.com/stal111/Forbidden-Arcanus/issues/9#issue-478801627
![arcanus missing](https://user-images.githubusercontent.com/53692357/62755799-a328c500-ba32-11e9-8fb7-47deca60df28.png)
compressed_items-1.14.4-1.0
https://github.com/stal111/Compressed-Items/issues/2#issue-478801845
![compressed missing](https://user-images.githubusercontent.com/53692357/62755842-cce1ec00-ba32-11e9-8a36-bdf292160f8d.png)
I'm not sure what the issue is... Is one meant to delete config. files when updating a mod?
Sorry to be a bother.

**Comment by VsnGamer** [comment]
Works fine for me, are there any errors in the logs ?

**Comment by bloodconfetti** [comment]
Uhm I'm not super sure how to check that for you, but stal111 was able to correct Forbidden Arcanus so they might be able to tell you the fix for yours? I can politely ask them if they have any advice if you'd like.

eta: there are a lot of errors in the Latest log but idk which mod they're from.

**Comment by VsnGamer** [comment]
1.14.4-1.3.11 was compiled with forge 1.14.4 - 28.0.11, maybe it just needs to be recompiled with the new version, try this one (extract jar and install normally)
[elevatorid-1.14.4-1.3.12.zip](https://github.com/VsnGamer/ElevatorMod/files/3485849/elevatorid-1.14.4-1.3.12.zip)

**Comment by bloodconfetti** [comment]
Sorry... I installed it like normal, but there's no elevator block tab, nor the blocks themselves. But my game is so broken right now I wouldn't be surprised if there was nothing you could do to fix it at the moment.

**Comment by VsnGamer** [comment]
No problem, can I have a log, just to take a look at?

**Comment by bloodconfetti** [comment]
[latest.log](https://github.com/VsnGamer/ElevatorMod/files/3486087/latest.log)
[debug.log](https://github.com/VsnGamer/ElevatorMod/files/3486089/debug.log)
[2019-08-08-3.log.gz](https://github.com/VsnGamer/ElevatorMod/files/3486091/2019-08-08-3.log.gz)
I hope any of these can help. If you need anything else, please let me know!

**Comment by ProsperCraft** [comment]
Forge .45 has breaking changes and many mods need to recompile for it or it breaks registration of blocks.

Have been fighting with this for over 12 hours now testing one mod at a time.

**Comment by ProsperCraft** [comment]
I already know compressed items and attained drops are a problem in that list.

**Comment by VsnGamer** [comment]
Can you try 1.14.4-1.5.1 and see if it works ?

**Comment by VsnGamer** [comment]
Closing unless anyone still has issues.
