### ISSUE TITLE
1.12.2-1.3.12 missing on CurseForge?

### ISSUE THREAD

**Issue by LemADEC** [VsnGamer/ElevatorMod#38]
It appears 1.12.2-1.3.12 was created but never pushed to CurseForge.

**Comment by VsnGamer** [comment]
1.3.12 fixes a rare spam in the console bug(#35) , I forgot to publish it because it affected so little people (and 1.14+ versions have this fix already)
If you need it I can publish it.
Thanks.

**Comment by LemADEC** [comment]
please do publish it

**Comment by VsnGamer** [comment]
Uploaded, please confirm fix
Thanks.
