### ISSUE TITLE
Error while using the elevator

### ISSUE THREAD

**Issue by juanlost** [VsnGamer/ElevatorMod#43]
I use forge + sponge in my server, get this error when someone teleport with the elevator block.
Forge 1.12.2 - 2838
SpongeForge 1.12.2 - 2838 - 7.1.7

https://pastebin.com/eWzpZZG8

[ElevatorMod error.txt](https://github.com/VsnGamer/ElevatorMod/files/3937189/ElevatorMod.error.txt)

Thanks! Have a nice day!

**Comment by VsnGamer** [comment]
What version of the mod are you using ?

**Comment by juanlost** [comment]
Solved updating the mod! I was using the 1.12.2-1.4.2 and give me the error, then i try with 1.3.11 and its all ok! The thing is that the number of the version its a little bit confusing for me.
Thanks for replying!

**Comment by VsnGamer** [comment]
It is explained on the curseforge page.
Thanks
