### ISSUE TITLE
[Bug/suggestion] Skip or lock invalid elevator targets

### ISSUE THREAD

**Issue by LorenaGdL** [VsnGamer/ElevatorMod#44]
Unsure if this is the intended behaviour or a bug/oversight. When you try to teleport and the next elevator is an invalid target (solid block/suffocating), instead of not teleporting at all, you teleport to the further next available elevator.

This prevents you from "locking"the elevators, and therefore constitutes a security breach in which any other player can add an elevator block to your own chain, and access restricted areas. Take a look at this scenario for a better explanation: [https://imgur.com/a/Ek8DDtd](https://imgur.com/a/Ek8DDtd). Imagine the wooden structure is your secured house (probably with mods like SecurityCraft). In the current version, if a hostile player puts the green elevator, he can directly access your theoretically secured area, by skipping the invalid red elevator and going down straight to the middle gray one. With the suggestion, such player would try to teleport down, but since the red elevator is unreachable, he just wouldn't teleport at all, preventing unauthorized access.

Let me know your thoughts. I'm providing a PR with these changes, that can be customized in the config in case anyone prefers the current behaviour.

(Of course unauthorized use of elevator could also be achieved by implemented private/public/team elevators, this is just a simple workaround)

**Comment by VsnGamer** [comment]
Working as intended, if a elevator is invalid it continues the search normally.

As you said, a config option can be implemented.
The thing is 99% of the times grief or access protection is needed FTB Teams is installed, and players claim entire chunks so thats not a problem.

Private elevators is a planned feature but I've not yet decided if it would be a mod system or a system witch uses FTB Teams.

Thanks for the report.

**Comment by LorenaGdL** [comment]
> As you said, a config option can be implemented but 99% of the times that protection is needed

What do you mean by "99% of the times that protection is needed"? What protection? I'm not talking at all about providing less protection, exactly the way around.

> FTB Teams is installed and players claim entire chunks so thats not a problem.

Installed? AFAIK, your mod doesn't require FTB to work.

Have you even taken a look at the provided PR?

**Comment by VsnGamer** [comment]
I did, the PR is good.

I said "needed", like on public servers normally owners install FTB teams to provide protection for the players, of course your PR adds more protection. (I got it that the scope of the PR was to provide better protection).

Maybe I didn't express myself clearly, sorry for that.

**Comment by VsnGamer** [comment]
Oh I see what I did wrong.

I messed up the commas in the first comment, I will fix it now.

Again, sorry for that.

**Comment by VsnGamer** [comment]
Please test new version and check if everything is working.
