### ISSUE TITLE
name broken at newest update

### ISSUE THREAD

**Issue by dagantang** [VsnGamer/ElevatorMod#46]
![2019-12-19_11 30 38](https://user-images.githubusercontent.com/32885622/71142691-19e09500-2253-11ea-93e6-88e056f86eba.png)

**Comment by VsnGamer** [comment]
It's working fine here, what forge version are you using ?

**Comment by dagantang** [comment]
forge version 2847

**Comment by VsnGamer** [comment]
Can you try this ?

[ElevatorMod-1.12.2-1.3.14.zip](https://github.com/VsnGamer/ElevatorMod/files/3984541/ElevatorMod-1.12.2-1.3.14.zip)

**Comment by dagantang** [comment]
![2019-12-20_00 47 20](https://user-images.githubusercontent.com/32885622/71191986-69aa7500-22c2-11ea-86eb-fb90f246c1fc.png)
![2019-12-20_00 47 32](https://user-images.githubusercontent.com/32885622/71191987-69aa7500-22c2-11ea-9406-3c0a3f6ddb85.png)
still wrong

**Comment by VsnGamer** [comment]
Weird, try this one.
[ElevatorMod-1.12.2-1.3.14-LANG_FIX_TEST.zip](https://github.com/VsnGamer/ElevatorMod/files/3984732/ElevatorMod-1.12.2-1.3.14-LANG_FIX_TEST.zip)

**Comment by dagantang** [comment]
![2019-12-20_01 23 54](https://user-images.githubusercontent.com/32885622/71194740-7382a700-22c7-11ea-9e36-37d5de3aaa1a.png)
Its fixed.thz

**Comment by VsnGamer** [comment]
Nice !
Will upload to curseforge now.
Thanks for the report.
