### ISSUE TITLE
Elevator limited to 10 blocks.

### ISSUE THREAD

**Issue by markbot2000** [VsnGamer/ElevatorMod#47]
I'm in survival and I cannot find the file to edit in the world folder.

**Comment by VsnGamer** [comment]
What version are you using ?

**Comment by markbot2000** [comment]
I’m using 1.14.4 Release version.

**Comment by VsnGamer** [comment]
You can find the config in:
`<your world folder>/serverconfig/elevatorid-server.toml`

**Comment by markbot2000** [comment]
The block limit is still 10 after changing in the world folder. Any fix?

**Comment by VsnGamer** [comment]
Do  you have any logs ? Or could you provide your specific elevator arrangement(distance, blocks in between, etc) ?

**Comment by markbot2000** [comment]
Like the logs from the .minecraft logs folder?

**Comment by VsnGamer** [comment]
Yes

**Comment by markbot2000** [comment]
[2019-02-10-1.log.gz](https://github.com/VsnGamer/ElevatorMod/files/4010790/2019-02-10-1.log.gz)

**Comment by VsnGamer** [comment]
12 lines ? That doesn't contain any useful information.

**Comment by markbot2000** [comment]
I’m not sure how to make it longer? i’m fairly new at modding. sorry

**Comment by VsnGamer** [comment]
Try loading the world, and try using the elevators and then send the log.

**Comment by markbot2000** [comment]
My apologies, the elevator was in the wrong block column. It works. I am so sorry

**Comment by layxa** [comment]
Hi. I'm on a 1.12.2 server and elevators are 10 blocks locked. I changed the config file many times, but when I load the server the config file seems to reset i don't know why

**Comment by VsnGamer** [comment]
Can you open a new issue with more information (logs, config, images, etc..) ?
