### ISSUE TITLE
May I use the textures of the elevators for a spinoff port to fabric

### ISSUE THREAD

**Issue by i509VCB** [VsnGamer/ElevatorMod#49]
I know the project is licensed under MIT but I wanted to ask about the textures. Note my implementation may refer to the codebase but will be mostly different to use the point of interest system.

**Comment by VsnGamer** [comment]
Sure !

**Comment by vico93** [comment]
Sorry the necropost, but @i509VCB are you still working on this fork?

**Comment by i509VCB** [comment]
Sadly no, kind of forgot
