### ISSUE TITLE
Crash on server load 1.6.0

### ISSUE THREAD

**Issue by lorilith** [VsnGamer/ElevatorMod#53]
MC Version: 1.15.2
Forge version: 31.1.1
Mod list: Only this (open elevtor 1.6.0 for 1.15.2)
Java version: 1.8.0 - 231, Windows

receiving this error on load
`[08:12:12] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.15.2`
`[08:12:12] [Server thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to load class xyz.vsngamer.elevatorid.ElevatorMod`
`java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IBlockColor`
`        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231] {}`
`        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_231] {}`
`        at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.1] {re:classloading}`

**Comment by NielsPilgaard** [comment]
Same issue here, but I thought you'd like the crash report: https://gist.github.com/NillerMedDild/ef3d7f66d1340602ef1b69d6b26138d1

**Comment by VsnGamer** [comment]
I see what's wrong
Should be fixed by tomorrow

**Comment by bluejorts** [comment]
Ditto here, thanks for the quick reply Vsn

**Comment by VsnGamer** [comment]
Please test version 1.6.1

**Comment by lorilith** [comment]
1.6.1 works great
