### ISSUE TITLE
[1.15.2-1.7.0] Client crash when going up elevator to Nature's Aura area

### ISSUE THREAD

**Issue by shortybsd** [VsnGamer/ElevatorMod#57]
**Minecraft:** 1.15.2
**Forge:** 31.1.18
**OpenBlocks Elevator:** 1.7.0
**Nature's Aura:** 23.3

When using elevator I receive the following [client crash](https://pastebin.com/Mkwe3QF2)

Casting particles on the elevator block crashes the client. Already reported to Nature's Aura and [he stated his mod wasn't the cause.](https://github.com/Ellpeck/NaturesAura/issues/94)

**Comment by VsnGamer** [comment]
Can you test this please ?
[elevatorid-1.15.2-1.7.1.zip](https://github.com/VsnGamer/ElevatorMod/files/4359413/elevatorid-1.15.2-1.7.1.zip)
Thanks.

**Comment by shortybsd** [comment]
Seemed to work with local server test. Sorry, I was going to push to modpack but needed permission e.t.c. for not using a build listed on Curse. I didn't get to test long (play for an hour or more) but I did warp around the map then came back to the spot where the issue usually happens. The problem is very sporadic on version 1.7.0 via Curse.
