### ISSUE TITLE
Unknown spam line in the log

### ISSUE THREAD

**Issue by kellixon** [VsnGamer/ElevatorMod#6]
MC 1.11.2, Forge 13.20.0.2298 (dev), ElevatorMod 1.3.0 (+ 60mods).
https://pastebin.com/pvjubS3v (6 line)
MC 1.11.2, Forge 13.20.0.2228 (stable), ElevatorMod 1.3.0 (1 mod).
https://pastebin.com/zQnfGttn (279 line)

**Comment by VsnGamer** [comment]
Hello !
I think I fixed it on the 2 last commits.
It was printing the source of the update.json page, I forgot that it must be the raw version.
Thanks for the report !

**Comment by VsnGamer** [comment]
Confirm the fix and report back to me plz !
Thanks !

**Comment by kellixon** [comment]
In version 1.3.1 no bugs and no spam (Forge 2228 and 2298). Everything works perfectly. Thank you.
