### ISSUE TITLE
Interaction Botania

### ISSUE THREAD

**Issue by novaexe** [VsnGamer/ElevatorMod#63]
interaction between elevator and botania's globetrotter sash causes the elevator to only work sometimes

MC 1.16.1

**Comment by VsnGamer** [comment]
Any logs/errors ?

**Comment by novaexe** [comment]
sry don't have any logs/errors because it doesn't crash, it works 3/10 times tho so it's incredibly annoying

**Comment by wrincewind** [comment]
I think i've got some more information on this, if it's related to what i'm doing - I found this out via Blood Magic's Living Armour, here: https://github.com/WayofTime/BloodMagic/issues/1738

basically, the Living armour and the Globetrotter's sash both provide a Jump Boost effect. I've tested with a vanilla Jump Boost potion and we have the same problem - if you jump too high, the elevator often does not recognise that you are trying to use it. Tapping jump VERY quickly (like, <1/10th of a second quickly) makes it more likely that the jump will register, and with the Bound Armour you can bypass it by sneak-jumping (as this cancels the Jump Boost effect).

For reference, I'm using Elevatorid-1.16.4-1.7.8, as part of the 'FTB Presents Direwolf20 for 1.16' Modpack.

**Comment by wrincewind** [comment]
Also, you can negate this by ensuring you always have a roof above your head (i.e. elevator, air, air, solid block) so your jump doesn't go out-of-bounds.

**Comment by VsnGamer** [comment]
The teleport is triggered just after jumping in this one, check if it helps with the issue.
[elevatorid-1.16.4-1.7.9-63-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/5760824/elevatorid-1.16.4-1.7.9-63-unzip-me.zip)

**Comment by Niner93R** [comment]
[After doing some testing,](https://streamable.com/sd5rcw) it seems this happens with most any item that applies high amounts of jump boost, regardless of mod. Was going to open a new issue but this seems relevant enough.

**Comment by VsnGamer** [comment]
Yes, wrincewind also found that, can you try the fix above ?
Thanks

**Comment by Niner93R** [comment]
Yes, [the fix works](https://streamable.com/1mo78a) even if jump boost effects are stacked or just alone.
