### ISSUE TITLE
Spam of Errors at the Log files

### ISSUE THREAD

**Issue by neriyac** [VsnGamer/ElevatorMod#66]
Hey,
for a long time I ignored this and now its lagging the server and apam the console and the Log file.
something is wrong with the mod and a lot of Devs told me to ask here what is wrong.

This is an example of Erroring messages:
https://paste.ubuntu.com/p/G2kKdmrNCh/

Full log file:
https://paste.gg/p/anonymous/077e23d341e54e339d1478b34a04855b/revisions

**Comment by VsnGamer** [comment]
Might(or not) be a sponge compatibility issue
This version is a bit old but I will try to fix it nevertheless

**Comment by VsnGamer** [comment]
Can you try this?
[ElevatorMod-1.12.2-1.4.3-LOGFIX.zip](https://github.com/VsnGamer/ElevatorMod/files/5214930/ElevatorMod-1.12.2-1.4.3-LOGFIX.zip)

**Comment by neriyac** [comment]
Hey, thank you for your respond!
I am trying it, will update in 24h.

**Comment by neriyac** [comment]
Well I have to say - all seems good!
I wish the Modpacks will upgtade their mods at the first place.
Thank you for your time!
