### ISSUE TITLE
1.15.2 Client Crash

### ISSUE THREAD

**Issue by MokahTGS** [VsnGamer/ElevatorMod#68]
Getting a crash loading the client:

Crash Log: https://pastebin.com/axizcnk6

Full Mod list: https://pastebin.com/sc6aneNA

Forge 31.2.41
elevatorid-1.15.2-1.7.1.jar

**Comment by VsnGamer** [comment]
Couldn't reproduce, probably a compatibility issue with another mod
![image](https://user-images.githubusercontent.com/18006201/94283205-9faf1080-ff48-11ea-8488-e404a02f1cfd.png)

**Comment by MokahTGS** [comment]
So I narrowed it down to Minecolonies and its dependancy, Structurize.  Can you replicate the crash with those installed?

**Comment by VsnGamer** [comment]
Can you try to update everything to the latest 1.15.2 versions ?
I was able to load all 3 mods just fine
![image](https://user-images.githubusercontent.com/18006201/95663221-4d1f4800-0b35-11eb-89fb-7a0e9e69831f.png)

**Comment by grandogarndo** [comment]
I just got the same error, with a different modlist. people online with this issue said it is optifine's fault, but removing it does nothing.

**Comment by grandogarndo** [comment]
i deleted the elevator mod and this crash happened:
https://pastebin.com/fVeuSU4Y

**Comment by VsnGamer** [comment]
@grandogarndo It's unlikely to be a problem with this mod since you removed it.
Looks like a Applied Energistics 2 crash although I'm not completely sure.

**Comment by MokahTGS** [comment]
I'm closing this since we don't use 1.15.2 and have since moved our server to 1.16.3.  This is no longer something I can test.  People will need to open their own issues.
