### ISSUE TITLE
Elevator completely invisible and unaccessable

### ISSUE THREAD

**Issue by jajajafeti** [VsnGamer/ElevatorMod#72]
I camouflaged the elevator with a Chisel & Bits carpet like item. And now its gone, the elevator is functional and blocks the space so I cant place another block there, but not visible, accessable nor has a hitbox. In the video you can see a piston can move it and gets visivle a short time, but thats all. Now I let my Turtle from CC tweaked dig the block aaaand the server crashed, but its still there. So I have to think of something else to remove it...
But I would suggest a config file, where you can blacklist camouflag items, tags and even complete mods like Chisel & Bits. 
And I play on 1.16.3

https://user-images.githubusercontent.com/61298096/104316879-68f00c80-54dd-11eb-8b52-74c2ac95c0fc.mp4

**Comment by VsnGamer** [comment]
This was fixed in #71 
Try using the latest version (1.16.4-1.7.9), it should also be compatible with 1.16.3
Thanks
