### ISSUE TITLE
Error while loading mod (v1.7.10, MC 1.16.3, Forge 34.1.42)

### ISSUE THREAD

**Issue by martymarty004** [VsnGamer/ElevatorMod#73]
**OpenBlocks Elevator version:** 1.7.10
**Minecraft Version:** 1.16.3
**Forge version:** 34.1.42

I just updated OpenBlocks Elevator to the latest version (1.7.10) and now it encounters an error on startup:

`Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File elevatorid-1.16.4-1.7.10.jar needs language provider javafml:35 or above to load
§7We have found 34.1`

**Comment by VsnGamer** [comment]
Can you try 1.7.11?
Thanks

**Comment by martymarty004** [comment]
Everything works now.
Thank you for the speed
