### ISSUE TITLE
Crash when coming home through END gate the first time [1.16.5]

### ISSUE THREAD

**Issue by Knito58** [VsnGamer/ElevatorMod#74]
Minecraft Version: 1.16.5
Forge: net.minecraftforge:36.0.1
elevatorid-1.16.5-1.7.11

https://pastebin.com/6P1A4qYN

Weird: I did not yet place any elevatorid elevator block.

**Comment by VsnGamer** [comment]
Can you try this fix?
[elevatorid-1.16.5-1.7.12-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/5860300/elevatorid-1.16.5-1.7.12-unzip-me.zip)

**Comment by Knito58** [comment]
Travelled through the END and back with it - no game crash this time. Everything fine.
