### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Sunekaer** [VsnGamer/ElevatorMod#79]
Crash log: https://gnomebot.dev/api/guild/file/303440391124942858/701513050833813661/819960037334057000/crash-2021-02-19_15.16.28-client.txt
Issue: client instantly crashes after placing elevator block in multiplayer server.

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/219

**Comment by VsnGamer** [comment]
Thanks for the report
@BamsTheSergal can you try this fix?
[elevatorid-1.16.5-1.7.13-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/6135324/elevatorid-1.16.5-1.7.13-unzip-me.zip)
Thanks
