### ISSUE TITLE
[Request] Slab elevators

### ISSUE THREAD

**Issue by chimericdream** [VsnGamer/ElevatorMod#80]
Pretty much what it says on the title. I'd love the ability to have a half-height block that was still an elevator.

**Comment by ghost** [comment]
Bump

I too think there is a call for slab style elevator blocks. Skyblock modpacks, for example, sensible people would make the floor from slabs to stop mob spawns and a square elevator block looks weird

**Comment by VsnGamer** [comment]
You can camouflage it with top and bottom slabs

**Comment by VsnGamer** [comment]
You probably already figured it out but you can camouflage them with bottom and top slabs.
