### ISSUE TITLE
Weird Texture Disappearance Issue

### ISSUE THREAD

**Issue by BrenMcdan** [VsnGamer/ElevatorMod#81]
Hello, this issue appears to occur when elevators from this mod are placed. As you can see I am able to look through the ground, and blocks such as glass, beds, plants, torches, crops, water, etc. completely disappear. This only occurs when looking in the direction of an elevator(s) and while the chunks with said elevator(s) are loaded. The mod version is the latest, being 1.7.13 for game version 1.16.5. Thank you for your time.
![2021-06-21_23 35 11](https://user-images.githubusercontent.com/86280077/122864121-aa38e380-d2e9-11eb-8202-5fd911ea5cf2.png)

Edit: I am using the modpack "Better Minecraft" with additional mods (cc-tweaked, immersive engineering, inventory tweaks, journeymap, pam's harvestcraft, refined storage, optifine)

**Comment by VsnGamer** [comment]
Can't reproduce, it might be a mod compatibility issue
Can you upload a log file?
Thanks

**Comment by dr0per250** [comment]
Hi! I'm suffering the same issue (I think). When look to some chunk with an elevator, its says in the chat "Open GL error 1281 (Invalid value)"

The mod list:
·securitycraft 1.5.23
·architectury 1.22.32 forge
·biomes op 13.1.0.482 uni..
·bookshelf 10.2.27
·Chisel-MC1.16.5-2.0.1-alpha.4
·CreativeCore_v2.2.1_mc1.16.5
·CTM-MC1.16.1-1.1.2.6
·CustomSkinLoader_Forge-14.13-SNAPSHOT-278
·elevatorid-1.16.5-1.7.13
·FallingTree-1.16.5-2.11.5
·ftb-library-forge-1605.3.2-build.64
·Hwyla-forge-1.10.11-B78_1.16.2
·jei-1.16.5-7.7.1.121
·journeymap-1.16.5-5.7.3
·mcw-bridges-1.0.6-mc1.16.5
·Morpheus-1.16.5-4.2.70
·OptiFine_1.16.5_HD_U_G8
·PlayerRevive_v2.0.0-pre04_mc1.16.5
·TerraForged-1.16.5-0.2.14
·voicechat-forge-1.16.5-1.7.7
·WAWLA-1.16.5-8.0.6

**Comment by SirGigaBalls** [comment]
any update on how to fix this or if any mod incompatibilities have been found that are causing this bug? Cant figure out how to fix it and is super annoying

**Comment by SirGigaBalls** [comment]
I have found the issue, the problem is with optifine. If you go into Options > Video Settings > Performance, turning off ‘Render Regions’ will fix the bug
