### ISSUE TITLE
Open GL error 1281

### ISSUE THREAD

**Issue by GweldigeSjig** [VsnGamer/ElevatorMod#84]
When placing an elevator i keep getting the "open GL error  1281" pop up in the chat, wich is quite annoying
![2021-11-04_18 40 39](https://user-images.githubusercontent.com/92528743/143472398-27b3574b-783d-4091-a19f-f658600e34ee.png)
.

**Comment by Tidy-Bear** [comment]
Same problem.
Causing by Optifine, can hide the msg by turning off 'Show GL Errors' at Options > Video Settings > Other.
However, the conflict still exist.

**Comment by teixeir3** [comment]
I added this mod to an install of better minecraft [plus] 1.16.5 with OptiFine HD U G8 and the same problem occurs. It seems to cause a graphical bug that makes certain blocks invisible. It became too difficult to work around so I uninstalled ElevatorMod for now. It would be great to have a fix.

**Comment by VsnGamer** [comment]
~~I think just by compiling with a newer version of forge fixed it, can anyone try this build to confirm?
[elevatorid-1.16.5-1.7.14-unzip-me.zip](https://github.com/VsnGamer/ElevatorMod/files/8311621/elevatorid-1.16.5-1.7.14-unzip-me.zip)~~

**Comment by VsnGamer** [comment]
See: https://github.com/VsnGamer/ElevatorMod/issues/81#issuecomment-977753283
