### ISSUE TITLE
game crash upon standing on elevator

### ISSUE THREAD

**Issue by VovelPunch** [VsnGamer/ElevatorMod#86]
[debug.log](https://github.com/VsnGamer/ElevatorMod/files/8009145/debug.log)
[latest.log](https://github.com/VsnGamer/ElevatorMod/files/8009146/latest.log)
Minecraft version: 1.16.5 
server using is using: mohist-1.16.5-936-server
forge: 36.2.26

**Comment by VsnGamer** [comment]
Caused by a [issue](https://github.com/cabaletta/baritone/issues/2148) in baritone, fixed [here](https://github.com/cabaletta/baritone/pull/3067) 
I guess you have to wait for a new 1.16 release
