### ISSUE TITLE
Elevator block being replaced when you right-click on it

### ISSUE THREAD

**Issue by Unimatrix36** [VsnGamer/ElevatorMod#88]
When I have a block in my hand and right-click on the elevator block, the elevator block will be replaced with the block I have in my hand.
It also makes the teleportation sound when it's being replaced.

Minecraft 1.18.2
Forge 40.0.32
elevatorid-1.18.2-1.8.4.jar

**Comment by Targren** [comment]
That's the camouflage function.  Right click with an empty hand and choose "Remove Camouflage" to undo it
