### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Lapiukas6** [VsnGamer/ElevatorMod#94]
Server crashes when using mod, worked before. Server now crashes. (developer) Friend told me that it seems to be a "cilent only mod"

**Comment by Lapiukas6** [comment]
I've gotten an update on the crash: "It caused errors because it tries to load classes that only exist on the client."

**Comment by VsnGamer** [comment]
This is likely due to using a newer version of Forge.
I just released an updated version of the mod that was compiled with Forge 1.19 - 41.0.98. Can you try that?
Thanks

**Comment by Lapiukas6** [comment]
I cant really try that as the server has been closed, sorry.
(sorry for being delay i was having some personal trouble)
