### ISSUE TITLE
Elevator Mod has failed to load correctly

### ISSUE THREAD

**Issue by Dustynzzz** [VsnGamer/ElevatorMod#95]
Minecraft V: 1.19
Forge V: 41.0.88
Mod error: java.reflect.InvocationTargetException: null
[latest.log](https://github.com/VsnGamer/ElevatorMod/files/9126146/latest.log)
[crash-2022-07-16_18.03.23-fml.txt](https://github.com/VsnGamer/ElevatorMod/files/9126147/crash-2022-07-16_18.03.23-fml.txt)

**Comment by VsnGamer** [comment]
Try a newer version of Forge
