### ISSUE TITLE
OpenGl error.

### ISSUE THREAD

**Issue by Dirmagnos** [VsnGamer/ElevatorMod#99]
I dont know why, but i start getting "OpenGL Error: 1281 (invalid value)" after i place any of the blocks that come with this mod(for as long as i am in vicinity of it). Removing block fixes it.
1.16.5 and OptiFine.
I used same client and same mod a year ago and everything was fine.

**Comment by codethinki** [comment]
look at #81 (you have to disable render regions in optifine)
